"""Kazakh display labels; original values remain stable in API requests."""
import re
from catalog import AUTOTUNE, REVERB, DELAY, PRODUCTION, DELIVERY, INSTRUMENTS, MIX_OPTIONS, STRUCTURES

LABELS = {}
def labels(values, text):
    translated = text.split('|')
    assert len(values) == len(translated), (len(values), len(translated))
    LABELS.update(zip(values, translated))

labels(AUTOTUNE, 'Жанрға сай автоматты|Өшіру — табиғи дауыс|Байқалмайтын дыбыс биіктігін түзету|Жеңіл әуезді автотюн|Күшті роботтық автотюн|Трэпке арналған жылдам автотюн|Дауыс формантын өзгерту|Вокодер|Токбокс')
labels(REVERB, 'Жанрға сай автоматты|Құрғақ — реверберациясыз|Шағын бөлме|Студиялық бөлме|Пластиналық реверберация|Үлкен зал|Ғибадатхана кеңістігі|Серіппелі реверберация|Жылтыраған реверберация|Кенет тоқтайтын реверберация|Қысқа күңгірт реверберация')
labels(DELAY, 'Жанрға сай автоматты|Өшіру — жаңғырықсыз|Қысқа қайталама жаңғырық|Ширек нота кідірісі|Сегіздік нота кідірісі|Нүктелі сегіздік кідіріс|Екі арна арасында ауысатын жаңғырық|Таспалық жаңғырық|Даб стиліндегі қайталама жаңғырық|Сөз соңындағы нәзік жаңғырық')
labels(PRODUCTION, 'Жанрға сай автоматты|Кәсіби студия — радиоға дайын өңдеу|Таза заманауи цифрлық студия|Жылы аналогтық студия|Көне таспалық студия|Жақын естілетін үй студиясы|Жанды концерт жазбасы|Шикі андеграунд жазбасы|Кассеталық лоу-фай жазбасы|Кең кинематографиялық студия|Жанды акустикалық бөлме|Құрғақ жақын микрофонды студия')
labels(DELIVERY, 'Легато — бірқалыпты жалғасқан тіркестер|Стаккато — қысқа үзік дыбыстар|Мелизма — буынды әуенмен әшекейлеу|Түзу дыбыс — вибратосыз|Жеңіл вибрато|Кең мәнерлі вибрато|Сыбырлап айту|Сөзбен баяндау|Жылдам рэп|Әуезді рэп|Қос қарқынды рэп|Дем аралас жақын орындау|Қуатты белтинг|Жұмсақ баяу әндету|Сұрақ-жауап орындау|Көмеймен айту|Йодль|Фальцет|Қырылдаған төмен дыбыс|Гроул — көмейлік ырыл|Айқайлап айту|Дәстүрлі әуендік әшекейлер')
labels(INSTRUMENTS, 'Домбыра|Қобыз|Қомуз|Дутар|Дойра|Бағлама|Тар|Каманча|Дарбука|Саз|Қанун|Ней|Уд|Аккордеон|Шаңқобыз|Морин хуур|Акустикалық гитара|Электр гитара|Нейлон ішекті гитара|Бұрмаланған гитара|Бас гитара|Контрабас|808 бас|Терең суббас|Аналогтық синтезатор|Жиіліктік синтезатор|Синтезатор арпеджиосы|Созылыңқы синтезатор|Фортепиано|Родс электрпианосы|Вурлитцер электрпианосы|Хаммонд органы|Шіркеу органы|Ішекті аспаптар|Жеке скрипка|Виолончель|Арфа|Үрмелі жез аспаптар|Керней|Тромбон|Валторна|Саксофон|Кларнет|Флейта|Гобой|Фагот|Барабан жиынтығы|Барабан машинасы|808 барабандары|909 барабандары|Трэп хай-хэты|Шапалақ|Қол соқпалы аспаптары|Конга|Бонго|Шейкер|Бубен|Литавра|Тайко|Табла|Ситар|Сантур|Маримба|Вибрафон|Калимба|Болат барабан|Қоңыраулы ксилофон|Созылыңқы хор дыбысы|Қиылған дыбыс үлгілері|Винил сыбдыры|Табиғи орта жазбасы')
for key, text in {
 'Компрессия': 'Автоматты|Табиғи динамика|Жеңіл біріктіруші компрессия|Серпінді параллель компрессия|Күшті ырғақты компрессия|Ырғаққа сай дыбысты бәсеңдету',
 'EQ / тон': 'Автоматты|Жылы төменгі-орта жиіліктер|Жарқын ауадай жоғарғы жиіліктер|Күңгірт жұмсақ жоғарғы жиіліктер|Таза теңгерімді жиіліктер|Орта жиіліктегі анық вокал|Терең басқа басымдық',
 'Сатурация': 'Автоматты|Таза — қанықтырусыз|Жеңіл таспалық жылылық|Лампалық қанықтыру|Кедір-бұдыр бұрмалану|Цифрлық үгітілген дыбыс',
 'Стерео': 'Автоматты|Жақын тар стерео|Кең стерео көрініс|Көне моно дыбыс|Орталық дауыс және кең қосалқы дауыс|Көлемді кеңістік',
 'Вокалдың микстегі орны': 'Автоматты|Алдыңғы жақын микрофонды дауыс|Аспаптармен араласқан дауыс|Алыстан естілетін арманшыл дауыс|Құрғақ орталық дауыс|Қабатталған қос дауыс',
 'Бэк-вокал': 'Автоматты|Қосалқы дауыссыз|Жеңіл қосарлау|Терция және квинта үндестігі|Кең хор сүйемелі|Сұрақ-жауап сүйемелі|Октавалық қосарлау|Қосымша лептер және вокал үзінділері',
 'Динамика': 'Автоматты|Бірқалыпты қуат|Жұмсақ шумақ — қуатты қайырма|Біртіндеп кинематографиялық өрлеу|Сирек шумақ — тығыз қайырма|Дропқа негізделген ауысу',
}.items(): labels(MIX_OPTIONS[key], text)
labels(STRUCTURES, 'Автоматты|Шумақ–Қайырма–Шумақ–Қайырма–Өтпелі бөлім–Қайырма–Аяқталу|Кіріспе–Шумақ–Қайырма алдындағы бөлім–Қайырма–Шумақ–Қайырма–Аяқталу|Кіріспе–Өрлеу–Дроп–Бәсеңдеу–Өрлеу–Дроп–Аяқталу|Шумақ–Ілмек–Шумақ–Ілмек–Өтпелі бөлім–Ілмек|Үздіксіз құрылым — қайырма қайталанбайды|Қысқа кіріспе–Шумақ–Қайырма–Аяқталу')
LABELS.update(dict(zip(['Energetic','Melancholic','Uplifting','Romantic','Dark','Peaceful','Epic','Nostalgic'], ['Қуатты','Мұңды','Рухтандыратын','Романтикалық','Күңгірт','Тыныш','Асқақ','Сағынышты'])))
LABELS.update({'English':'Ағылшынша','Русский':'Орысша','العربية':'Арабша','Тілге сай / Auto':'Тілге сай автоматты','Cyrillic':'Кирилл жазуы','Latin':'Латын жазуы','Arabic':'Араб жазуы', 'Auto':'Автоматты'})

# Established genre names and place names are transliterated; descriptors translated.
WORDS = dict(pair.split('=') for pair in ('trap=трэп|hip-hop=хип-хоп|rap=рэп|pop=поп|rock=рок|jazz=джаз|folk=фолк|soul=соул|house=хаус|techno=техно|trance=транс|ambient=эмбиент|classical=классикалық|cinematic=кинематографиялық|acoustic=акустикалық|traditional=дәстүрлі|modern=заманауи|contemporary=заманауи|minimal=минималистік|melodic=әуезді|dark=күңгірт|warm=жылы|bright=жарқын|deep=терең|soft=жұмсақ|hard=қатты|slow=баяу|fast=жылдам|electronic=электрондық|experimental=эксперименттік|instrumental=аспаптық|orchestral=оркестрлік|vocal=вокалдық|female=әйел|male=еркек|choral=хорлық|strings=ішекті аспаптар|drums=барабандар|bass=бас|guitar=гитара|piano=фортепиано|synth=синтезатор|synths=синтезаторлар|dombra=домбыра|kobyz=қобыз|kazakh=қазақша|turkic=түркі|california=Калифорния|los=Лос|angeles=Анджелес|atlanta=Атланта|memphis=Мемфис|detroit=Детройт|houston=Хьюстон|miami=Майами|new=жаңа|york=Йорк|london=Лондон|paris=Париж|berlin=Берлин|tokyo=Токио|chicago=Чикаго|brazil=Бразилия|almaty=Алматы|istanbul=Ыстанбұл|studio=студия|production=дыбыс өңдеуі|polished=ұқыпты өңделген|spacious=кеңістікті|groove=ырғақ|rhythm=ырғақ|rhythmic=ырғақты|percussion=соқпалы аспаптар|leads=жетекші әуендер|lead=жетекші|ensemble=ансамбль|arrangement=аранжировка|ornamentation=әшекейлер|and=және|with=қатысқан|no=жоқ|auto=автоматты|straight=түзу|swung=свингті|waltz=вальс|flowing=бірқалыпты|half-time=жарты қарқын|double-time=қос қарқын|shuffle=шаффл|syncopated=синкопалы|polyrhythmic=көпырғақты').split('|'))
PHRASES = {'West Coast':'Батыс жағалау','laid-back bounce':'еркін серпінді ырғақ','low-end':'төменгі жиіліктер','rolling 808s':'домалаған 808 бас','triplet hi-hats':'триольді хай-хэт','offbeat pocket':'әлсіз үлеске басымдық','chopped-and-screwed feel':'қиылып баяулатылған дыбыс','bass-heavy club bounce':'басқа бай клубтық серпін','UK':'Британдық','R&B':'ритм-н-блюз','EDM':'электрондық би музыкасы','Lo-Fi':'лоу-фай','Q-Pop':'кью-поп'}
WORDS.update(dict(pair.split('=') for pair in ('gritty=кедір-бұдыр|punchy=соққысы анық|grit=кедір-бұдырлық|samples=дыбыс үлгілері|sampling=үлгілерді қолдану|syncopated=синкопалы|hooks=есте қалатын әуендер|hook=әуендік ілмек|bounce=серпін|sunny=шуақты|southern=оңтүстік|offbeat=әлсіз үлестегі|flow=ағым|eerie=үрейлі|soulful=сезімге толы|urban=қалалық|french=француз|sparse=сирек|sinister=үрейлі|sliding=сырғымалы|energetic=қуатты|distorted=бұрмаланған|pulse=ырғақ соғысы|night-drive=түнгі сапар|atmosphere=атмосфера|festive=мерекелік|toy=той|komuz-led=қомуз жетекшілік ететін|doira=дойра|dutar=дутар|muqam-inspired=мұқамға негізделген|baglama=бағлама|darbuka=дарбука|tar=тар|kamancha=каманча|accordion=аккордеон|dance=би|classic=классикалық|swing=свинг|depth=тереңдік|filtered=сүзгіленген|sunset=күн батардағы|underground=андеграунд|south=оңтүстік|africa=Африка|log-drum=бөрене барабан|afro=африкалық|futuristic=футуристік|machines=дыбыс машиналары|hypnotic=баурайтын|industrial=индустриялық|driving=қарқынды|energy=қуат|broken=үзік|collective=ұжымдық|intimate=жақын|sway=тербеліс|sunlit=шуақты|tone=үн|arena=үлкен сахна|sound=дыбыс|british=британдық|roots-oriented=дәстүрге негізделген|live=жанды|band=топ|raw=шикі|outlaw=еркін|twang=ішектің өткір үні|layered=қабатталған|color=реңк|alternative=балама|texture=дыбыс өрнегі|lush=бай|feel=әсер|concert=концерт|hall=зал|scoring=музыка жазу|stage=сахна|clarity=айқындық|chamber=камералық|bowed-string=ысқылы ішекті|string-band=ішекті аспаптар тобы|storytelling=оқиғаны баяндау|moody=көңіл-күйлі|space=кеңістік|minimalist=минималистік|electronics=электроника|delicate=нәзік|environmental=табиғи орта|ambience=кеңістік әсері|phrasing=музыкалық тіркестер|regional=аймақтық|brass=жез үрмелі аспаптар|precise=дәл|detail=нақтылық|instrumentation=аспап құрамы|textured=өрнекті').split('|')))
LABELS.update({'Қазақша / Turkic':'Қазақша / түркі музыкасы','Hip-Hop / Rap':'Хип-хоп / рэп','Alternative / Indie':'Балама / инди','R&B / Soul':'Ритм-н-блюз / соул','Bass / EDM':'Бас / электрондық би музыкасы','Drum & Bass':'Драм-н-бейс','UK Garage / Breaks':'Британдық гэридж / брейкс','Synth / Retro':'Синтезатор / ретро','Ambient / Downtempo':'Эмбиент / баяу электроника','Blues / Funk':'Блюз / фанк','Country / Americana':'Кантри / американа','Folk / Acoustic':'Фолк / акустика','Reggae / Caribbean':'Регги / Кариб музыкасы','Africa / Global':'Африка / әлем музыкасы','Asia / Middle East':'Азия / Таяу Шығыс','Classical / Cinematic':'Классикалық / кино музыкасы','Gospel / Vocal':'Госпел / вокал','Auto / жанрға сай':'Жанрға сай автоматты'})
LABELS.update({'Kazakh Folk':'Қазақ халық музыкасы','Kyrgyz folk':'Қырғыз халық музыкасы','Uzbek pop':'Өзбек поп музыкасы','Uzbek maqom':'Өзбек мақамы','Uyghur muqam':'Ұйғыр мұқамы','Turkish folk':'Түрік халық музыкасы','Anatolian rock':'Анадолы рок музыкасы','Azerbaijani mugham':'Әзербайжан мұғамы','Turkmen folk':'Түрікмен халық музыкасы','Tatar pop':'Татар поп музыкасы','Bashkir folk':'Башқұрт халық музыкасы','Sakha folk':'Саха халық музыкасы','Synthwave':'Синтвейв','Retrowave':'Ретровейв','Darksynth':'Дарксинт','Lo-fi hip-hop':'Лоу-фай хип-хоп','Boom bap':'Бум-бэп','G-funk':'Джи-фанк','West Coast trap':'Батыс жағалау трэбі','West Coast hip-hop':'Батыс жағалау хип-хопы','East Coast hip-hop':'Шығыс жағалау хип-хопы'})
WORDS.update(dict(pair.split('=') for pair in ('country=кантри|blues=блюз|funk=фанк|punk=панк|metal=метал|reggae=регги|gospel=госпел|drill=дрилл|phonk=фонк|lo-fi=лоу-фай|synthwave=синтвейв|indie=инди|downtempo=баяу электроника|latin=латын|drift=дрифт|cloud=бұлтты|emo=эмо|progressive=прогрессивті|psychedelic=психоделиялық|garage=гараждық|symphonic=симфониялық|gothic=готикалық|death=дэт|black=блэк|heavy=хэви|power=қуатты|singer-songwriter=авторлық ән|meditation=медитациялық|music=музыка|soundtrack=саундтрек|film=фильм|score=музыка|solo=жеке|opera=опера|operetta=оперетта|romantic=романтикалық|baroque=барокко|choir=хор|choir=хор|sacred=рухани|string=ішекті|quartet=квартет|electric=электрлік|vintage=көне|nostalgic=сағынышты|peaceful=тыныш|uplifting=рухтандыратын|epic=асқақ|california=Калифорния|angeles=Анджелес').split('|')))
def kz(value):
    if value in LABELS: return LABELS[value]
    for original, translated in PHRASES.items(): value = value.replace(original, translated)
    def word(match):
        token = match.group()
        if token.lower() in WORDS: return WORDS[token.lower()]
        # Borrowed specialist names retain their pronunciation in Cyrillic.
        token = token.lower()
        for a,b in [('sh','ш'),('ch','ч'),('ph','ф'),('th','т'),('qu','кв'),('ee','и'),('oo','у'),('ou','ау')]: token=token.replace(a,b)
        return token.translate(str.maketrans(dict(zip('abcdefghijklmnopqrstuvwxyz', ['а','б','к','д','е','ф','г','х','и','ж','к','л','м','н','о','п','к','р','с','т','у','в','в','кс','и','з']))))
    return re.sub(r'[A-Za-z]+(?:-[A-Za-z]+)*', word, value)

VOICE_TYPES = {'Еркек дауысы':'male lead vocal','Әйел дауысы':'female lead vocal','Дуэт':'male and female duet','Хор':'blended choir','Дауыссыз':'instrumental only, no vocals'}
VOICE_RANGES = {
 'Еркек дауысы': {'Автоматты':'natural male register','Бас':'deep male bass','Баритон':'male baritone','Тенор':'male tenor','Контртенор':'male countertenor'},
 'Әйел дауысы': {'Автоматты':'natural female register','Контральто':'female contralto','Альт':'female alto','Меццо-сопрано':'female mezzo-soprano','Сопрано':'female soprano'},
 'Дуэт': {'Үйлесімді диапазондар':'complementary male and female registers'},
 'Хор': {'Аралас хор':'mixed choir registers','Ерлер хоры':'male choir registers','Әйелдер хоры':'female choir registers'},
}
TIMBRES = {'Қоңыр':'warm dark rounded','Мұрындық':'nasal focused','Жарқын':'bright forward','Барқыт':'velvety smooth','Қарлығыңқы':'husky textured','Таза':'clear clean','Нәзік':'delicate soft','Дем аралас':'airy breathy','Жібектей':'silky fluid','Қуатты резонансты':'full resonant','Металдық':'metallic penetrating','Түтінді':'smoky intimate'}
